name: Brandon Setter Films
favicon: null
layout_spectrum: 0.5795383276417851
typography_spectrum: 0.7499985371250659
title: Brandon Setter Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c3c1ce'
    - '#303030'
    - '#426777'
    - '#618f9f'
    - '#663b35'
  brandStrength: 0.875
  lightness: 1
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
