name: Brandon Setter Films
favicon: null
layout_spectrum: 0.5795383276417851
typography_spectrum: 0.7499985371250659
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6327529593836516
  lightness: 0.4766308879479766
  saturation: 0.5182861613575369
  rhythmicContrast: 0.6638646048959345
purpose: []
